<?php

/**
 * @file
 * Contains exposed_filter_block_for_block_v.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function exposed_filter_block_for_block_v_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the exposed_filter_block_for_block_v module.
    case 'help.page.exposed_filter_block_for_block_v':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Embed Exposed Filter for Block views as a block.') . '</p>';
      return $output;

    default:
  }
}
